/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountDeleteCard: typeof import('./inertia/components/AccountDeleteCard.vue')['default']
    AccountEmailCard: typeof import('./inertia/components/AccountEmailCard.vue')['default']
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Card: typeof import('./inertia/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./inertia/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./inertia/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./inertia/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./inertia/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./inertia/components/ui/card/CardTitle.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Select: typeof import('./inertia/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./inertia/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./inertia/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./inertia/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./inertia/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./inertia/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./inertia/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./inertia/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./inertia/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./inertia/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./inertia/components/ui/select/SelectValue.vue')['default']
  }
}
